// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_IMAGEWHITENER_OGMANEO_SCHEMAS_H_
#define FLATBUFFERS_GENERATED_IMAGEWHITENER_OGMANEO_SCHEMAS_H_

#include "flatbuffers/flatbuffers.h"

#include "Helpers_generated.h"

namespace ogmaneo {
namespace schemas {

struct ImageWhitener;

struct ImageWhitener FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT__SIZE = 4,
    VT__RESULT = 6
  };
  const ogmaneo::schemas::int2 *_size() const { return GetStruct<const ogmaneo::schemas::int2 *>(VT__SIZE); }
  ogmaneo::schemas::int2 *mutable__size() { return GetStruct<ogmaneo::schemas::int2 *>(VT__SIZE); }
  const ogmaneo::schemas::Image2D *_result() const { return GetPointer<const ogmaneo::schemas::Image2D *>(VT__RESULT); }
  ogmaneo::schemas::Image2D *mutable__result() { return GetPointer<ogmaneo::schemas::Image2D *>(VT__RESULT); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<ogmaneo::schemas::int2>(verifier, VT__SIZE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT__RESULT) &&
           verifier.VerifyTable(_result()) &&
           verifier.EndTable();
  }
};

struct ImageWhitenerBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add__size(const ogmaneo::schemas::int2 *_size) { fbb_.AddStruct(ImageWhitener::VT__SIZE, _size); }
  void add__result(flatbuffers::Offset<ogmaneo::schemas::Image2D> _result) { fbb_.AddOffset(ImageWhitener::VT__RESULT, _result); }
  ImageWhitenerBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  ImageWhitenerBuilder &operator=(const ImageWhitenerBuilder &);
  flatbuffers::Offset<ImageWhitener> Finish() {
    auto o = flatbuffers::Offset<ImageWhitener>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<ImageWhitener> CreateImageWhitener(flatbuffers::FlatBufferBuilder &_fbb,
    const ogmaneo::schemas::int2 *_size = 0,
    flatbuffers::Offset<ogmaneo::schemas::Image2D> _result = 0) {
  ImageWhitenerBuilder builder_(_fbb);
  builder_.add__result(_result);
  builder_.add__size(_size);
  return builder_.Finish();
}

}  // namespace schemas
}  // namespace ogmaneo

#endif  // FLATBUFFERS_GENERATED_IMAGEWHITENER_OGMANEO_SCHEMAS_H_
