// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_SPARSEFEATURESSTDP_OGMANEO_SCHEMAS_H_
#define FLATBUFFERS_GENERATED_SPARSEFEATURESSTDP_OGMANEO_SCHEMAS_H_

#include "flatbuffers/flatbuffers.h"

#include "Helpers_generated.h"

namespace ogmaneo {
namespace schemas {

struct VisibleSTDPLayerDesc;

struct VisibleSTDPLayer;

struct SparseFeaturesSTDPDesc;

struct SparseFeaturesSTDP;

MANUALLY_ALIGNED_STRUCT(4) VisibleSTDPLayerDesc FLATBUFFERS_FINAL_CLASS {
 private:
  ogmaneo::schemas::int2 _size_;
  int32_t _radius_;
  uint8_t _ignoreMiddle_;
  int8_t __padding0;
  int16_t __padding1;
  float _weightAlpha_;

 public:
  VisibleSTDPLayerDesc() { memset(this, 0, sizeof(VisibleSTDPLayerDesc)); }
  VisibleSTDPLayerDesc(const VisibleSTDPLayerDesc &_o) { memcpy(this, &_o, sizeof(VisibleSTDPLayerDesc)); }
  VisibleSTDPLayerDesc(const ogmaneo::schemas::int2 &__size, int32_t __radius, uint8_t __ignoreMiddle, float __weightAlpha)
    : _size_(__size), _radius_(flatbuffers::EndianScalar(__radius)), _ignoreMiddle_(flatbuffers::EndianScalar(__ignoreMiddle)), __padding0(0), __padding1(0), _weightAlpha_(flatbuffers::EndianScalar(__weightAlpha)) { (void)__padding0; (void)__padding1; }

  const ogmaneo::schemas::int2 &_size() const { return _size_; }
  ogmaneo::schemas::int2 &mutable__size() { return _size_; }
  int32_t _radius() const { return flatbuffers::EndianScalar(_radius_); }
  void mutate__radius(int32_t __radius) { flatbuffers::WriteScalar(&_radius_, __radius); }
  uint8_t _ignoreMiddle() const { return flatbuffers::EndianScalar(_ignoreMiddle_); }
  void mutate__ignoreMiddle(uint8_t __ignoreMiddle) { flatbuffers::WriteScalar(&_ignoreMiddle_, __ignoreMiddle); }
  float _weightAlpha() const { return flatbuffers::EndianScalar(_weightAlpha_); }
  void mutate__weightAlpha(float __weightAlpha) { flatbuffers::WriteScalar(&_weightAlpha_, __weightAlpha); }
};
STRUCT_END(VisibleSTDPLayerDesc, 20);

struct VisibleSTDPLayer FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT__DERIVEDINPUT = 4,
    VT__WEIGHTS = 6,
    VT__HIDDENTOVISIBLE = 8,
    VT__VISIBLETOHIDDEN = 10,
    VT__REVERSERADII = 12
  };
  const ogmaneo::schemas::DoubleBuffer2D *_derivedInput() const { return GetPointer<const ogmaneo::schemas::DoubleBuffer2D *>(VT__DERIVEDINPUT); }
  ogmaneo::schemas::DoubleBuffer2D *mutable__derivedInput() { return GetPointer<ogmaneo::schemas::DoubleBuffer2D *>(VT__DERIVEDINPUT); }
  const ogmaneo::schemas::DoubleBuffer3D *_weights() const { return GetPointer<const ogmaneo::schemas::DoubleBuffer3D *>(VT__WEIGHTS); }
  ogmaneo::schemas::DoubleBuffer3D *mutable__weights() { return GetPointer<ogmaneo::schemas::DoubleBuffer3D *>(VT__WEIGHTS); }
  const ogmaneo::schemas::float2 *_hiddenToVisible() const { return GetStruct<const ogmaneo::schemas::float2 *>(VT__HIDDENTOVISIBLE); }
  ogmaneo::schemas::float2 *mutable__hiddenToVisible() { return GetStruct<ogmaneo::schemas::float2 *>(VT__HIDDENTOVISIBLE); }
  const ogmaneo::schemas::float2 *_visibleToHidden() const { return GetStruct<const ogmaneo::schemas::float2 *>(VT__VISIBLETOHIDDEN); }
  ogmaneo::schemas::float2 *mutable__visibleToHidden() { return GetStruct<ogmaneo::schemas::float2 *>(VT__VISIBLETOHIDDEN); }
  const ogmaneo::schemas::int2 *_reverseRadii() const { return GetStruct<const ogmaneo::schemas::int2 *>(VT__REVERSERADII); }
  ogmaneo::schemas::int2 *mutable__reverseRadii() { return GetStruct<ogmaneo::schemas::int2 *>(VT__REVERSERADII); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT__DERIVEDINPUT) &&
           verifier.VerifyTable(_derivedInput()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT__WEIGHTS) &&
           verifier.VerifyTable(_weights()) &&
           VerifyField<ogmaneo::schemas::float2>(verifier, VT__HIDDENTOVISIBLE) &&
           VerifyField<ogmaneo::schemas::float2>(verifier, VT__VISIBLETOHIDDEN) &&
           VerifyField<ogmaneo::schemas::int2>(verifier, VT__REVERSERADII) &&
           verifier.EndTable();
  }
};

struct VisibleSTDPLayerBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add__derivedInput(flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _derivedInput) { fbb_.AddOffset(VisibleSTDPLayer::VT__DERIVEDINPUT, _derivedInput); }
  void add__weights(flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer3D> _weights) { fbb_.AddOffset(VisibleSTDPLayer::VT__WEIGHTS, _weights); }
  void add__hiddenToVisible(const ogmaneo::schemas::float2 *_hiddenToVisible) { fbb_.AddStruct(VisibleSTDPLayer::VT__HIDDENTOVISIBLE, _hiddenToVisible); }
  void add__visibleToHidden(const ogmaneo::schemas::float2 *_visibleToHidden) { fbb_.AddStruct(VisibleSTDPLayer::VT__VISIBLETOHIDDEN, _visibleToHidden); }
  void add__reverseRadii(const ogmaneo::schemas::int2 *_reverseRadii) { fbb_.AddStruct(VisibleSTDPLayer::VT__REVERSERADII, _reverseRadii); }
  VisibleSTDPLayerBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  VisibleSTDPLayerBuilder &operator=(const VisibleSTDPLayerBuilder &);
  flatbuffers::Offset<VisibleSTDPLayer> Finish() {
    auto o = flatbuffers::Offset<VisibleSTDPLayer>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<VisibleSTDPLayer> CreateVisibleSTDPLayer(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _derivedInput = 0,
    flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer3D> _weights = 0,
    const ogmaneo::schemas::float2 *_hiddenToVisible = 0,
    const ogmaneo::schemas::float2 *_visibleToHidden = 0,
    const ogmaneo::schemas::int2 *_reverseRadii = 0) {
  VisibleSTDPLayerBuilder builder_(_fbb);
  builder_.add__reverseRadii(_reverseRadii);
  builder_.add__visibleToHidden(_visibleToHidden);
  builder_.add__hiddenToVisible(_hiddenToVisible);
  builder_.add__weights(_weights);
  builder_.add__derivedInput(_derivedInput);
  return builder_.Finish();
}

struct SparseFeaturesSTDPDesc FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT__HIDDENSIZE = 4,
    VT__INHIBITIONRADIUS = 6,
    VT__BIASALPHA = 8,
    VT__ACTIVERATIO = 10,
    VT__GAMMA = 12,
    VT__INITWEIGHTRANGE = 14,
    VT__VISIBLELAYERDESCS = 16
  };
  const ogmaneo::schemas::int2 *_hiddenSize() const { return GetStruct<const ogmaneo::schemas::int2 *>(VT__HIDDENSIZE); }
  ogmaneo::schemas::int2 *mutable__hiddenSize() { return GetStruct<ogmaneo::schemas::int2 *>(VT__HIDDENSIZE); }
  int32_t _inhibitionRadius() const { return GetField<int32_t>(VT__INHIBITIONRADIUS, 0); }
  bool mutate__inhibitionRadius(int32_t __inhibitionRadius) { return SetField(VT__INHIBITIONRADIUS, __inhibitionRadius); }
  float _biasAlpha() const { return GetField<float>(VT__BIASALPHA, 0.0f); }
  bool mutate__biasAlpha(float __biasAlpha) { return SetField(VT__BIASALPHA, __biasAlpha); }
  float _activeRatio() const { return GetField<float>(VT__ACTIVERATIO, 0.0f); }
  bool mutate__activeRatio(float __activeRatio) { return SetField(VT__ACTIVERATIO, __activeRatio); }
  float _gamma() const { return GetField<float>(VT__GAMMA, 0.0f); }
  bool mutate__gamma(float __gamma) { return SetField(VT__GAMMA, __gamma); }
  const ogmaneo::schemas::float2 *_initWeightRange() const { return GetStruct<const ogmaneo::schemas::float2 *>(VT__INITWEIGHTRANGE); }
  ogmaneo::schemas::float2 *mutable__initWeightRange() { return GetStruct<ogmaneo::schemas::float2 *>(VT__INITWEIGHTRANGE); }
  const flatbuffers::Vector<const VisibleSTDPLayerDesc *> *_visibleLayerDescs() const { return GetPointer<const flatbuffers::Vector<const VisibleSTDPLayerDesc *> *>(VT__VISIBLELAYERDESCS); }
  flatbuffers::Vector<const VisibleSTDPLayerDesc *> *mutable__visibleLayerDescs() { return GetPointer<flatbuffers::Vector<const VisibleSTDPLayerDesc *> *>(VT__VISIBLELAYERDESCS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<ogmaneo::schemas::int2>(verifier, VT__HIDDENSIZE) &&
           VerifyField<int32_t>(verifier, VT__INHIBITIONRADIUS) &&
           VerifyField<float>(verifier, VT__BIASALPHA) &&
           VerifyField<float>(verifier, VT__ACTIVERATIO) &&
           VerifyField<float>(verifier, VT__GAMMA) &&
           VerifyField<ogmaneo::schemas::float2>(verifier, VT__INITWEIGHTRANGE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT__VISIBLELAYERDESCS) &&
           verifier.Verify(_visibleLayerDescs()) &&
           verifier.EndTable();
  }
};

struct SparseFeaturesSTDPDescBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add__hiddenSize(const ogmaneo::schemas::int2 *_hiddenSize) { fbb_.AddStruct(SparseFeaturesSTDPDesc::VT__HIDDENSIZE, _hiddenSize); }
  void add__inhibitionRadius(int32_t _inhibitionRadius) { fbb_.AddElement<int32_t>(SparseFeaturesSTDPDesc::VT__INHIBITIONRADIUS, _inhibitionRadius, 0); }
  void add__biasAlpha(float _biasAlpha) { fbb_.AddElement<float>(SparseFeaturesSTDPDesc::VT__BIASALPHA, _biasAlpha, 0.0f); }
  void add__activeRatio(float _activeRatio) { fbb_.AddElement<float>(SparseFeaturesSTDPDesc::VT__ACTIVERATIO, _activeRatio, 0.0f); }
  void add__gamma(float _gamma) { fbb_.AddElement<float>(SparseFeaturesSTDPDesc::VT__GAMMA, _gamma, 0.0f); }
  void add__initWeightRange(const ogmaneo::schemas::float2 *_initWeightRange) { fbb_.AddStruct(SparseFeaturesSTDPDesc::VT__INITWEIGHTRANGE, _initWeightRange); }
  void add__visibleLayerDescs(flatbuffers::Offset<flatbuffers::Vector<const VisibleSTDPLayerDesc *>> _visibleLayerDescs) { fbb_.AddOffset(SparseFeaturesSTDPDesc::VT__VISIBLELAYERDESCS, _visibleLayerDescs); }
  SparseFeaturesSTDPDescBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SparseFeaturesSTDPDescBuilder &operator=(const SparseFeaturesSTDPDescBuilder &);
  flatbuffers::Offset<SparseFeaturesSTDPDesc> Finish() {
    auto o = flatbuffers::Offset<SparseFeaturesSTDPDesc>(fbb_.EndTable(start_, 7));
    return o;
  }
};

inline flatbuffers::Offset<SparseFeaturesSTDPDesc> CreateSparseFeaturesSTDPDesc(flatbuffers::FlatBufferBuilder &_fbb,
    const ogmaneo::schemas::int2 *_hiddenSize = 0,
    int32_t _inhibitionRadius = 0,
    float _biasAlpha = 0.0f,
    float _activeRatio = 0.0f,
    float _gamma = 0.0f,
    const ogmaneo::schemas::float2 *_initWeightRange = 0,
    flatbuffers::Offset<flatbuffers::Vector<const VisibleSTDPLayerDesc *>> _visibleLayerDescs = 0) {
  SparseFeaturesSTDPDescBuilder builder_(_fbb);
  builder_.add__visibleLayerDescs(_visibleLayerDescs);
  builder_.add__initWeightRange(_initWeightRange);
  builder_.add__gamma(_gamma);
  builder_.add__activeRatio(_activeRatio);
  builder_.add__biasAlpha(_biasAlpha);
  builder_.add__inhibitionRadius(_inhibitionRadius);
  builder_.add__hiddenSize(_hiddenSize);
  return builder_.Finish();
}

inline flatbuffers::Offset<SparseFeaturesSTDPDesc> CreateSparseFeaturesSTDPDescDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const ogmaneo::schemas::int2 *_hiddenSize = 0,
    int32_t _inhibitionRadius = 0,
    float _biasAlpha = 0.0f,
    float _activeRatio = 0.0f,
    float _gamma = 0.0f,
    const ogmaneo::schemas::float2 *_initWeightRange = 0,
    const std::vector<const VisibleSTDPLayerDesc *> *_visibleLayerDescs = nullptr) {
  return CreateSparseFeaturesSTDPDesc(_fbb, _hiddenSize, _inhibitionRadius, _biasAlpha, _activeRatio, _gamma, _initWeightRange, _visibleLayerDescs ? _fbb.CreateVector<const VisibleSTDPLayerDesc *>(*_visibleLayerDescs) : 0);
}

struct SparseFeaturesSTDP FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT__HIDDENACTIVATIONS = 4,
    VT__HIDDENSTATES = 6,
    VT__HIDDENBIASES = 8,
    VT__HIDDENSIZE = 10,
    VT__INHIBITIONRADIUS = 12,
    VT__HIDDENSUMMATIONTEMP = 14,
    VT__BIASALPHA = 16,
    VT__ACTIVERATIO = 18,
    VT__GAMMA = 20,
    VT__VISIBLELAYERDESCS = 22,
    VT__VISIBLELAYERS = 24
  };
  const ogmaneo::schemas::DoubleBuffer2D *_hiddenActivations() const { return GetPointer<const ogmaneo::schemas::DoubleBuffer2D *>(VT__HIDDENACTIVATIONS); }
  ogmaneo::schemas::DoubleBuffer2D *mutable__hiddenActivations() { return GetPointer<ogmaneo::schemas::DoubleBuffer2D *>(VT__HIDDENACTIVATIONS); }
  const ogmaneo::schemas::DoubleBuffer2D *_hiddenStates() const { return GetPointer<const ogmaneo::schemas::DoubleBuffer2D *>(VT__HIDDENSTATES); }
  ogmaneo::schemas::DoubleBuffer2D *mutable__hiddenStates() { return GetPointer<ogmaneo::schemas::DoubleBuffer2D *>(VT__HIDDENSTATES); }
  const ogmaneo::schemas::DoubleBuffer2D *_hiddenBiases() const { return GetPointer<const ogmaneo::schemas::DoubleBuffer2D *>(VT__HIDDENBIASES); }
  ogmaneo::schemas::DoubleBuffer2D *mutable__hiddenBiases() { return GetPointer<ogmaneo::schemas::DoubleBuffer2D *>(VT__HIDDENBIASES); }
  const ogmaneo::schemas::int2 *_hiddenSize() const { return GetStruct<const ogmaneo::schemas::int2 *>(VT__HIDDENSIZE); }
  ogmaneo::schemas::int2 *mutable__hiddenSize() { return GetStruct<ogmaneo::schemas::int2 *>(VT__HIDDENSIZE); }
  int32_t _inhibitionRadius() const { return GetField<int32_t>(VT__INHIBITIONRADIUS, 0); }
  bool mutate__inhibitionRadius(int32_t __inhibitionRadius) { return SetField(VT__INHIBITIONRADIUS, __inhibitionRadius); }
  const ogmaneo::schemas::DoubleBuffer2D *_hiddenSummationTemp() const { return GetPointer<const ogmaneo::schemas::DoubleBuffer2D *>(VT__HIDDENSUMMATIONTEMP); }
  ogmaneo::schemas::DoubleBuffer2D *mutable__hiddenSummationTemp() { return GetPointer<ogmaneo::schemas::DoubleBuffer2D *>(VT__HIDDENSUMMATIONTEMP); }
  float _biasAlpha() const { return GetField<float>(VT__BIASALPHA, 0.0f); }
  bool mutate__biasAlpha(float __biasAlpha) { return SetField(VT__BIASALPHA, __biasAlpha); }
  float _activeRatio() const { return GetField<float>(VT__ACTIVERATIO, 0.0f); }
  bool mutate__activeRatio(float __activeRatio) { return SetField(VT__ACTIVERATIO, __activeRatio); }
  float _gamma() const { return GetField<float>(VT__GAMMA, 0.0f); }
  bool mutate__gamma(float __gamma) { return SetField(VT__GAMMA, __gamma); }
  const flatbuffers::Vector<const VisibleSTDPLayerDesc *> *_visibleLayerDescs() const { return GetPointer<const flatbuffers::Vector<const VisibleSTDPLayerDesc *> *>(VT__VISIBLELAYERDESCS); }
  flatbuffers::Vector<const VisibleSTDPLayerDesc *> *mutable__visibleLayerDescs() { return GetPointer<flatbuffers::Vector<const VisibleSTDPLayerDesc *> *>(VT__VISIBLELAYERDESCS); }
  const flatbuffers::Vector<flatbuffers::Offset<VisibleSTDPLayer>> *_visibleLayers() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<VisibleSTDPLayer>> *>(VT__VISIBLELAYERS); }
  flatbuffers::Vector<flatbuffers::Offset<VisibleSTDPLayer>> *mutable__visibleLayers() { return GetPointer<flatbuffers::Vector<flatbuffers::Offset<VisibleSTDPLayer>> *>(VT__VISIBLELAYERS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT__HIDDENACTIVATIONS) &&
           verifier.VerifyTable(_hiddenActivations()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT__HIDDENSTATES) &&
           verifier.VerifyTable(_hiddenStates()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT__HIDDENBIASES) &&
           verifier.VerifyTable(_hiddenBiases()) &&
           VerifyField<ogmaneo::schemas::int2>(verifier, VT__HIDDENSIZE) &&
           VerifyField<int32_t>(verifier, VT__INHIBITIONRADIUS) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT__HIDDENSUMMATIONTEMP) &&
           verifier.VerifyTable(_hiddenSummationTemp()) &&
           VerifyField<float>(verifier, VT__BIASALPHA) &&
           VerifyField<float>(verifier, VT__ACTIVERATIO) &&
           VerifyField<float>(verifier, VT__GAMMA) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT__VISIBLELAYERDESCS) &&
           verifier.Verify(_visibleLayerDescs()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT__VISIBLELAYERS) &&
           verifier.Verify(_visibleLayers()) &&
           verifier.VerifyVectorOfTables(_visibleLayers()) &&
           verifier.EndTable();
  }
};

struct SparseFeaturesSTDPBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add__hiddenActivations(flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenActivations) { fbb_.AddOffset(SparseFeaturesSTDP::VT__HIDDENACTIVATIONS, _hiddenActivations); }
  void add__hiddenStates(flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenStates) { fbb_.AddOffset(SparseFeaturesSTDP::VT__HIDDENSTATES, _hiddenStates); }
  void add__hiddenBiases(flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenBiases) { fbb_.AddOffset(SparseFeaturesSTDP::VT__HIDDENBIASES, _hiddenBiases); }
  void add__hiddenSize(const ogmaneo::schemas::int2 *_hiddenSize) { fbb_.AddStruct(SparseFeaturesSTDP::VT__HIDDENSIZE, _hiddenSize); }
  void add__inhibitionRadius(int32_t _inhibitionRadius) { fbb_.AddElement<int32_t>(SparseFeaturesSTDP::VT__INHIBITIONRADIUS, _inhibitionRadius, 0); }
  void add__hiddenSummationTemp(flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenSummationTemp) { fbb_.AddOffset(SparseFeaturesSTDP::VT__HIDDENSUMMATIONTEMP, _hiddenSummationTemp); }
  void add__biasAlpha(float _biasAlpha) { fbb_.AddElement<float>(SparseFeaturesSTDP::VT__BIASALPHA, _biasAlpha, 0.0f); }
  void add__activeRatio(float _activeRatio) { fbb_.AddElement<float>(SparseFeaturesSTDP::VT__ACTIVERATIO, _activeRatio, 0.0f); }
  void add__gamma(float _gamma) { fbb_.AddElement<float>(SparseFeaturesSTDP::VT__GAMMA, _gamma, 0.0f); }
  void add__visibleLayerDescs(flatbuffers::Offset<flatbuffers::Vector<const VisibleSTDPLayerDesc *>> _visibleLayerDescs) { fbb_.AddOffset(SparseFeaturesSTDP::VT__VISIBLELAYERDESCS, _visibleLayerDescs); }
  void add__visibleLayers(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<VisibleSTDPLayer>>> _visibleLayers) { fbb_.AddOffset(SparseFeaturesSTDP::VT__VISIBLELAYERS, _visibleLayers); }
  SparseFeaturesSTDPBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SparseFeaturesSTDPBuilder &operator=(const SparseFeaturesSTDPBuilder &);
  flatbuffers::Offset<SparseFeaturesSTDP> Finish() {
    auto o = flatbuffers::Offset<SparseFeaturesSTDP>(fbb_.EndTable(start_, 11));
    return o;
  }
};

inline flatbuffers::Offset<SparseFeaturesSTDP> CreateSparseFeaturesSTDP(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenActivations = 0,
    flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenStates = 0,
    flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenBiases = 0,
    const ogmaneo::schemas::int2 *_hiddenSize = 0,
    int32_t _inhibitionRadius = 0,
    flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenSummationTemp = 0,
    float _biasAlpha = 0.0f,
    float _activeRatio = 0.0f,
    float _gamma = 0.0f,
    flatbuffers::Offset<flatbuffers::Vector<const VisibleSTDPLayerDesc *>> _visibleLayerDescs = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<VisibleSTDPLayer>>> _visibleLayers = 0) {
  SparseFeaturesSTDPBuilder builder_(_fbb);
  builder_.add__visibleLayers(_visibleLayers);
  builder_.add__visibleLayerDescs(_visibleLayerDescs);
  builder_.add__gamma(_gamma);
  builder_.add__activeRatio(_activeRatio);
  builder_.add__biasAlpha(_biasAlpha);
  builder_.add__hiddenSummationTemp(_hiddenSummationTemp);
  builder_.add__inhibitionRadius(_inhibitionRadius);
  builder_.add__hiddenSize(_hiddenSize);
  builder_.add__hiddenBiases(_hiddenBiases);
  builder_.add__hiddenStates(_hiddenStates);
  builder_.add__hiddenActivations(_hiddenActivations);
  return builder_.Finish();
}

inline flatbuffers::Offset<SparseFeaturesSTDP> CreateSparseFeaturesSTDPDirect(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenActivations = 0,
    flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenStates = 0,
    flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenBiases = 0,
    const ogmaneo::schemas::int2 *_hiddenSize = 0,
    int32_t _inhibitionRadius = 0,
    flatbuffers::Offset<ogmaneo::schemas::DoubleBuffer2D> _hiddenSummationTemp = 0,
    float _biasAlpha = 0.0f,
    float _activeRatio = 0.0f,
    float _gamma = 0.0f,
    const std::vector<const VisibleSTDPLayerDesc *> *_visibleLayerDescs = nullptr,
    const std::vector<flatbuffers::Offset<VisibleSTDPLayer>> *_visibleLayers = nullptr) {
  return CreateSparseFeaturesSTDP(_fbb, _hiddenActivations, _hiddenStates, _hiddenBiases, _hiddenSize, _inhibitionRadius, _hiddenSummationTemp, _biasAlpha, _activeRatio, _gamma, _visibleLayerDescs ? _fbb.CreateVector<const VisibleSTDPLayerDesc *>(*_visibleLayerDescs) : 0, _visibleLayers ? _fbb.CreateVector<flatbuffers::Offset<VisibleSTDPLayer>>(*_visibleLayers) : 0);
}

}  // namespace schemas
}  // namespace ogmaneo

#endif  // FLATBUFFERS_GENERATED_SPARSEFEATURESSTDP_OGMANEO_SCHEMAS_H_
